# Generated by Django 4.1.7 on 2023-03-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cartitem_delete_cartitems_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
