# Generated by Django 4.1.7 on 2023-03-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
