# Generated by Django 4.1.7 on 2023-03-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit68', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
